<?php

namespace PortfolioBundle\Repository;

/**
 * PhotoCouvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCouvertureRepository extends \Doctrine\ORM\EntityRepository
{
}
