<?php

namespace GestioProjetBundle\Repository;

/**
 * conditatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conditatureRepository extends \Doctrine\ORM\EntityRepository
{
}
