<?php

namespace SmartStart\GestioProjetBundle\Repository;

/**
 * documentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class documentationRepository extends \Doctrine\ORM\EntityRepository
{
}
