<?php

namespace GestioProjetBundle\Repository;

/**
 * proprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proprietaireRepository extends \Doctrine\ORM\EntityRepository
{
}
