<?php

namespace QuestionnaireBundle\Repository;

/**
 * CategorieQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieQuizRepository extends \Doctrine\ORM\EntityRepository
{






}
