<?php

namespace QuestionnaireBundle\Repository;

/**
 * ContactQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
