<?php

namespace QuestionnaireBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findpayeDQL(){
        $query = $this ->getEntityManager()

            -> createQuery("SELECT  m as n ,COUNT(m.id)as bcount   
            FROM QuestionnaireBundle:Evaluation m
                        
                     GROUP BY m.libelle 
             ");

        return $query ->getResult();

    }
}
