<?php

namespace QuestionnaireBundle\Repository;

/**
 * Passage_questionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Passage_questionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
