<?php

namespace ForumBundle\Repository;

/**
 * Commentaire_ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_ForumRepository extends \Doctrine\ORM\EntityRepository
{
}
