<?php

namespace ForumBundle\Repository;

/**
 * Forum_ReactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forum_ReactionRepository extends \Doctrine\ORM\EntityRepository
{
}
