<?php

namespace ForumBundle\Repository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends \Doctrine\ORM\EntityRepository
{
}
