<?php

namespace ForumBundle\Repository;

/**
 * SavedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedRepository extends \Doctrine\ORM\EntityRepository
{
}
