<?php

namespace EventBundle\Repository;

/**
 * CathEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CathEventRepository extends \Doctrine\ORM\EntityRepository
{
}
