<?php

namespace EventBundle\Repository;

/**
 * ComentEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentEventRepository extends \Doctrine\ORM\EntityRepository
{
}
